name: sync-dl

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/pigzillaaaaa/daddylive.git

      - name: Fetch upstream main branch
        run: |
          git fetch upstream main

      - name: Preserve your workflows
        run: |
          mv .github/workflows ../workflows_backup

      - name: Checkout upstream files
        run: |
          git checkout upstream/main -- .

      - name: Restore your workflows
        run: |
          rm -rf .github/workflows
          mv ../workflows_backup .github/workflows

      - name: Commit and push changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Synchronize Success"
          git push --force
